server:
  port: 8000
spring:
  h2:
    console:
      enabled: true
wmtipp:
  admin:
    login: admin
    password: wichtig
    
---
spring:
  profiles: filedb
  datasource:
    url: jdbc:h2:file:C:\Users\JannisLaptop\Dropbox\studieren\softwareengineeniring\praktikum\test.db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa.hibernate.ddl-auto: update
    